name: CI/CD KnowledgeBase

on:
  push:
    tags:
      - "v*.*.*" # Chỉ chạy khi push tag dạng vX.Y.Z

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        shell: bash
        run: |
          IMAGE_NAME=minvoicesys/knowlegae-base
          VERSION=${GITHUB_REF#refs/tags/v}  # Lấy version từ tag
          echo "Building image: $IMAGE_NAME:$VERSION"
          docker build -t $IMAGE_NAME:$VERSION .
          docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest

      - name: Push Docker image
        shell: bash
        run: |
          IMAGE_NAME=minvoicesys/knowlegae-base
          VERSION=${GITHUB_REF#refs/tags/v}
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/minvoice/knowlegebase
            docker compose pull
            docker compose up -d

      - name: Notify Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: "5702962241"
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "✅ Build & Push Docker image minvoicesys/knowlegae-base thành công! Version: ${{ github.ref#refs/tags/v }}"

      - name: Notify Telegram Failure
        if: failure() # Chỉ chạy khi job thất bại
        uses: appleboy/telegram-action@master
        with:
          to: "5702962241"
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "❌ Build & Push Docker image minvoicesys/knowlegae-base thất bại! Version: ${{ github.ref#refs/tags/v }}. Kiểm tra workflow ngay!"
